#!/bin/bash

# Welcome to TweakSign, a new way to sign tweaks and verify their security. Built by nathanaccidentally.
# Copyright (c) 2017 Nathan Goodwin and licensed under the MIT licinse.
# These lines must be included in any forks or redistributions and this project may not be claimed as your own.

if [ -n "$1" ]; then
    echo "Got folder from input. Attempting to sign it.";
    cd $1
fi

if [ -n "$2" ]; then
    echo "Sorry, but tweaksign cannot sign more than one folder at a time.";
fi

echo "Checking if you have dpkg installed..."
if dpkg --help >/dev/null ; then
	echo "Dpkg is installed. Will finish process."
else
	echo "Seems like dpkg isn't installed, TweakSign cannot work without it. Please install dpkg and try again."
fi

echo "Signing tweak..."
sleep 1

file="DEBIAN"
if [ -d "$file" ]
then
	echo "File is a Debian archive."
else
	echo "File is not a Debian archive."
	exit
fi

previousSig="DEBIAN/signature"
if [ -f "$previousSig" ]
then
	echo "Previous signature found."
	rm -f DEBIAN/signature
	sleep .5
else
	echo "Previous tweak signature not found."
	mkdir DEBIAN
	sleep .3
fi

echo "Writing bundle id from control file..."
bundleIdentifier=$(sed '1!d' DEBIAN/control)
echo "$bundleIdentifier"
echo "$bundleIdentifier" >> DEBIAN/signature
echo "" >> DEBIAN/signature

echo "Writing MD5 to signature..."
controlMd5=$(md5 DEBIAN/control)
echo "$controlMd5"
echo "Control MD5: $controlMd5" >> DEBIAN/signature

echo "Finished writing MD5 signature of control file."

echo "Writing SHA256 to signature..."
controlSHA256=$(shasum -a 256 DEBIAN/control)
echo "$controlSHA256"
echo "Control SHA256: $controlSHA256" >> DEBIAN/signature

checkForPostinst="DEBIAN/postinst"
if [ -f "$checkForPostinst" ]
then
	echo "Postinst script found."
	postinstMD5=$(MD5 DEBIAN/postinst)
	echo "$postinstMD5"
	echo "Postinst MD5: $postinstMD5" >> DEBIAN/signature

	postinstSHA256=$(shasum -a 256 DEBIAN/postinst)
	echo "$postinstSHA256"
	echo "Postinst SHA256: $postinstSHA256" >> DEBIAN/signature
else
	echo "Postinst script not found."
fi

checkForPrerm="DEBIAN/prerm"
if [ -f "$checkForPrerm" ]
then
	echo "Prerm script found."
	prermMD5=$(MD5 DEBIAN/prerm)
	echo "$prermMD5"
	echo "Prerm MD5: $prermMD5" >> DEBIAN/signature

	prermSHA256=$(shasum -a 256 DEBIAN/prerm)
	echo "$prermSHA256"
	echo "Prerm SHA256: $prermSHA256" >> DEBIAN/signature
else
	echo "Prerm script not found."
fi

checkForExtrainst="DEBIAN/extrainst_"
if [ -f "$checkForExtrainst" ]
then
	echo "extrainst_ script found."
	extrainstMD5=$(MD5 DEBIAN/extrainst_)
	echo "$extrainstMD5"
	echo "extrainst_ MD5: $extrainstMD5" >> DEBIAN/signature

	extrainstSHA256=$(shasum -a 256 DEBIAN/extrainst_)
	echo "$extrainstSHA256"
	echo "extrainst_ SHA256: $extrainstSHA256" >> DEBIAN/signature
else
	echo "Prerm script not found."
fi

echo "Signing .xm files..."
sleep .5
find . -name '*.xm' -exec md5 >> DEBIAN/signature {} \;

echo "Signing .dylib files..."
sleep .5
find . -name '*.dylib' -exec md5 >> DEBIAN/signature {} \;

echo "" >> DEBIAN/signature
echo "<--- End of file hashes --->" >> DEBIAN/signature
echo "" >> DEBIAN/signature

echo "Getting Author name from control package..."

authorName=$(sed '8!d' DEBIAN/control)
echo "$authorName"
echo "$authorName" >> DEBIAN/signature

echo "" >> DEBIAN/signature
echo "<--- End of control stuff --->" >> DEBIAN/signature
echo "" >> DEBIAN/signature

echo "Generating 8 digit key."
superSafeAndSecureKey=$(cat /dev/random | LC_CTYPE=C tr -dc "[:alpha:]" | head -c 8)
echo "Your key = $superSafeAndSecureKey"
echo "Your key = $superSafeAndSecureKey" >> DEBIAN/signature

echo "Changing permissions of signature..."
chflags hidden DEBIAN/signature
chmod 000 DEBIAN/signature
chmod a-w DEBIAN/signature

echo "Building package..."
echo -n "Would you like to use theos or dpkg to build package. Use 't' for theos and 'd' for dpkg. "
read answer
if echo "$answer" | grep -iq "^t" ;then
    make package
    echo "Done!"
else
    dpkg -b $PWD
    echo "Done!"
fi

exit
