#!/bin/bash

# Welcome to TweakSign, a new way to sign tweaks and verify their security. Built by nathanaccidentally.
# Copyright (c) 2017 Nathan Goodwin and licensed under the MIT licinse.
# These lines must be included in any forks or redistributions and this project may not be claimed as your own.

if [ -n "$1" ]; then
    echo "Signing multiple packages at the same time is not permitted."; exit
fi

echo "Checking if you have dpkg installed..."
if dpkg --help >/dev/null ; then
	echo "Dpkg is installed. Will finish process."
else
	echo "Seems like dpkg isn't installed, TweakSign cannot work without it. Please install dpkg and try again."
fi

echo "Signing tweak..."
sleep 1

file="DEBIAN"
if [ -d "$file" ]
then
	echo "File is a Debian archive."
else
	echo "File is not a Debian archive."
	exit
fi

previousSig="DEBIAN/signature"
if [ -f "$previousSig" ]
then
	echo "Previous signature found."
	rm -f DEBIAN/signature
	sleep .5
else
	echo "Previous tweak signature not found."
	mkdir DEBIAN
	sleep .3
fi

echo "Writing bundle id from control file..."
bundleIdentifier=$(sed '1!d' DEBIAN/control)
echo "$bundleIdentifier"
echo "$bundleIdentifier" >> DEBIAN/signature
echo "" >> DEBIAN/signature

echo "Writing MD5 to signature..."
controlMd5=$(md5 DEBIAN/control)
echo "$controlMd5"
echo "Control MD5: $controlMd5" >> DEBIAN/signature

echo "Finished writing MD5 signature of control file."

echo "Writing SHA1 to signature..."
controlSha1=$(openssl sha1 DEBIAN/control)
echo "$controlSha1"
echo "Control SHA1: $controlSha1" >> DEBIAN/signature

checkForPostinst="DEBIAN/postinst"
if [ -f "$checkForPostinst" ]
then
	echo "Postinst script found."
	postinstMD5=$(MD5 DEBIAN/postinst)
	echo "$postinstMD5"
	echo "Postinst MD5: $postinstMD5" >> DEBIAN/signature

	postinstSha1=$(openssl sha1 DEBIAN/postinst)
	echo "$postinstSha1"
	echo "Postinst SHA1: $postinstSha1" >> DEBIAN/signature
else
	echo "Postinst script not found."
fi

checkForPrerm="DEBIAN/prerm"
if [ -f "$checkForPrerm" ]
then
	echo "Prerm script found."
	prermMD5=$(MD5 DEBIAN/prerm)
	echo "$prermMD5"
	echo "Prerm MD5: $prermMD5" >> DEBIAN/signature

	prermSha1=$(openssl sha1 DEBIAN/prerm)
	echo "$prermSha1"
	echo "Prerm SHA1: $prermSha1" >> DEBIAN/signature
else
	echo "Prerm script not found."
fi

echo "Signing .xm files..."
sleep .5
find . -name '*.xm' -exec md5 >> DEBIAN/signature {} \;

echo "" >> DEBIAN/signature
echo "<--- End of file hashes --->" >> DEBIAN/signature
echo "" >> DEBIAN/signature

echo "Getting Author name from control package..."

authorName=$(sed '8!d' DEBIAN/control)
echo "$authorName"
echo "$authorName" >> DEBIAN/signature

echo "" >> DEBIAN/signature
echo "<--- End of control stuff --->" >> DEBIAN/signature
echo "" >> DEBIAN/signature

echo "Generating secure key used to install package..."
superSafeAndSecureKey=$(cat /dev/random | LC_CTYPE=C tr -dc "[:alpha:]" | head -c 8)
echo "Your secure key = $superSafeAndSecureKey"
echo "Your secure key = $superSafeAndSecureKey" >> DEBIAN/signature

echo "Building package..."
echo -n "Would you like to use theos or dpkg to build package. Use 't' for theos and 'd' for dpkg. "
read answer
if echo "$answer" | grep -iq "^t" ;then
    make package
    echo "Done!"
else
    dpkg -b $PWD
    echo "Done!"
fi

exit