#!/bin/bash

# Welcome to TweakSign, a new way to sign tweaks and verify their security. Built by nathanaccidentally.
# Copyright (c) 2017 Nathan Goodwin and licensed under the MIT licinse.
# These lines must be included in any forks or redistributions and this project may not be claimed as your own.

echo "Checking if you have dpkg installed..."
if dpkg --help >/dev/null ; then
    echo "Dpkg is installed. Will finish process."
else
    echo "Dpkg is not installed and is required for TweakSign to work properly. Please install and try again."
    exit
fi

if [ -n "$1" ]; then
    echo "Recieved file from input. Extracting...";
    mkdir DEBIAN
    dpkg -e $1 DEBIAN
    echo "Extracted deb file."
else
    echo "No deb file recieved. Assuming you're in signed tweak folder.";
fi

if [ -n "$2" ]; then
    echo "Sorry, TweakSign currently doesn't support verifying more than 1 deb package at a time.";
fi

echo "Verifying signature of package..."

doesSigExists="DEBIAN/signature"
if [ -f "$doesSigExists" ]
then
	echo "Signature found."
else
	echo "Signature not found."
	exit
fi

secureKeyLineTitle="Your secure key = "
secureKeyFromSig=$(grep "$secureKeyLineTitle" DEBIAN/signature)
grep "$secureKeyLineTitle" DEBIAN/signature >/dev/null

echo -n "This is the key I got from the signature: $secureKeyFromSig. Would you like to continue? "
read answer
if echo "$answer" | grep -iq "^y" ;then
    echo "OK. Will keep doing verification."
else
    echo "Quitting."
    exit
fi

controlMD5LineTitle="Control MD5: "
controlmd5FromSig=$(grep "$controlMD5LineTitle" DEBIAN/signature)
currentControlMd5FromSystem=$(md5 DEBIAN/control)
grep "$controlMD5LineTitle" DEBIAN/signature

if [[ "$controlmd5FromSig" =~ "$currentControlMd5FromSystem" ]]; then
	echo "Valid Control MD5..."
else
	echo "⚠️ Invalid Control MD5.⚠️ "
	exit
fi

controlSHA1LineTitle="Control SHA1: "
controlSHA1FromSig=$(grep "$controlSHA1LineTitle" DEBIAN/signature)
currentControlSHA1FromSystem=$(openssl sha1 DEBIAN/control)
grep "$controlSHA1LineTitle" DEBIAN/signature

if [[ "$controlSHA1FromSig" =~ "$currentControlSHA1FromSystem" ]]; then
	echo "Valid Control SHA1..."
else
	echo "⚠️ Invalid Control SHA1.⚠️ "
	exit
fi

    checkForPostinst="DEBIAN/postinst"
    if [ -f "$checkForPostinst" ]
    then

    postinstMD5LineTitle="Postinst MD5: "
    postinstmd5FromSig=$(grep "$postinstMD5LineTitle" DEBIAN/signature)
    currentPostinstMd5FromSystem=$(md5 DEBIAN/postinst)
    grep "$postinstMD5LineTitle" DEBIAN/signature
    
    if [[ "$postinstmd5FromSig" =~ "$currentPostinstMd5FromSystem" ]]; then
    	echo "Valid Postinst MD5..."
    else
    	echo "⚠️ Invalid Postinst MD5.⚠️ "
    	exit
    fi


    postinstSHA1LineTitle="Postinst SHA1: "
    postinstSHA1FromSig=$(grep "$postinstSHA1LineTitle" DEBIAN/signature)
    currentPostinstSHA1FromSystem=$(openssl sha1 DEBIAN/postinst)
    grep "$postinstSHA1LineTitle" DEBIAN/signature
    
    if [[ "$postinstSHA1FromSig" =~ "$currentPostinstSHA1FromSystem" ]]; then
    	echo "Valid Postinst SHA1..."
    else
    	echo "⚠️ Invalid Postinst SHA1.⚠️ "
    	exit
    fi
else
	echo "Postinst script not found."
fi

echo "Trying to verify .xm files..."
find . -name '*.xm' -exec md5 {} \;
echo -n "Do these hashes look right? I can't verify them automatically (y / n) "
read answer
if echo "$answer" | grep -iq "^y" ;then
    echo "OK. Done."
else
    echo "Quitting."
    exit
fi
